
FROM python:3.10.12

WORKDIR /dressing_virtuel

COPY ./requirements.txt /dressing_virtuel/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /dressing_virtuel/requirements.txt

COPY ./api/api_classification_model.py /dressing_virtuel/app

COPY ./classification/classification_model.py /dressing_virtuel/classification

CMD ["fastapi", "run", "api/api_classification_model.py", "--port", "5000"]