{
 "title": "FASTAPI Webservices",
 "tags": [ "api" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "APIs Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"Models API\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job=\"Celery API\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job=\"Postgre API\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Table Log - Error Messages Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tcount(*) as cnt_error, \r\n\tregexp_substr(message, '\\s([\\w.]+)\\s', 1, 1) AS extracted_api,\r\n\t$__timeGroupAlias(\"created_at\",5m)\r\nFROM \r\n\tlogs \r\nWHERE \"level\" = 'ERROR' and message like '%api.%' and $__timeFilter(created_at)\r\ngroup BY time, extracted_api\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "not 200 requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "changes(http_requests_total{handler!=\"none\",status!=\"2xx\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "200 requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "changes(http_requests_total{instance=~\".+\",instance!=\"/metrics\",status=\"2xx\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}