import os

#PG
SERVER = os.getenv("PG_API_SERVER")
PORT = os.getenv("PG_API_PORT")
ENDPOINT = os.getenv("PG_API_ENDPONT")

PG_URI = f"http://{SERVER}:{PORT}/{ENDPOINT}"
PG_API_KEY = os.getenv("PG_API_KEY")

#OBJECT DETECTION
SERVER = os.getenv("OBJ_DETECTION_API_SERVER")
PORT = os.getenv("OBJ_DETECTION_API_PORT")
ENDPOINT = os.getenv("OBJ_DETECTION_API_ENDPOINT")

OBJ_DETECTION_URI = f"http://{SERVER}:{PORT}/{ENDPOINT}"
OBJ_DETECTION_API_KEY = os.getenv("OBJ_DETECTION_API_KEY")

#FACE RECOGINITION
SERVER = os.getenv("FACE_RECOGNITION_API_SERVER")
PORT = os.getenv("FACE_RECOGNITION_API_PORT")
ENDPOINT = os.getenv("FACE_RECOGNITION_API_ENDPOINT")

FACE_RECOGNITION_URI = f"http://{SERVER}:{PORT}/{ENDPOINT}"
FACE_RECOGNITION_API_KEY = os.getenv("FACE_RECOGNITION_API_KEY")

#SEGMENTATION
SERVER = os.getenv("SEGMENTATION_API_SERVER")
PORT = os.getenv("SEGMENTATION_API_PORT")
ENDPOINT = os.getenv("SEGMENTATION_API_ENDPOINT")

SEGMENTATION_URI = f"http://{SERVER}:{PORT}/{ENDPOINT}"
SEGMENTATION_API_KEY = os.getenv("SEGMENTATION_API_KEY")

#CLASSIFICATION
SERVER = os.getenv("CLASSIFICATION_API_SERVER")
PORT = os.getenv("CLASSIFICATION_API_PORT")
ENDPOINT = os.getenv("CLASSIFICATION_API_ENDPOINT")

CLASSIFICATION_URI = f"http://{SERVER}:{PORT}/{ENDPOINT}"
CLASSIFICATION_API_KEY = os.getenv("CLASSIFICATION_API_KEY")